#!/usr/bin/env bash
set -e

REPO_ROOT="${1:-}"
THEME_NAME="${2:-}"

if [ -z "$REPO_ROOT" ] || [ -z "$THEME_NAME" ]; then
  echo "Usage: apply_theme.sh <repo_root> <theme_name>"
  exit 1
fi

SAGA_CONFIG_DIR="$HOME/.config/saga"
THEMES_DIR="$SAGA_CONFIG_DIR/themes"
WIDGETS_DIR="$SAGA_CONFIG_DIR/widgets"
FUTURE_RENDERER_DIR="$WIDGETS_DIR/saga-ui"
HYPR_CONFIG_DIR="$HOME/.config/hypr"
HYPR_THEME_FILE="$HYPR_CONFIG_DIR/theme.conf"
WOFI_CONFIG_DIR="$HOME/.config/wofi"
WOFI_STYLE_FILE="$WOFI_CONFIG_DIR/style.css"
SWAYNC_CONFIG_DIR="$HOME/.config/swaync"
SWAYNC_STYLE_FILE="$SWAYNC_CONFIG_DIR/style.css"
SDDM_THEME_ROOT="/usr/share/sddm/themes"
SDDM_THEME_CONF_DIR="/etc/sddm.conf.d"
SDDM_THEME_CONF_FILE="$SDDM_THEME_CONF_DIR/20-saga-theme.conf"

# Theme lookup: exact name first, then saga-<name> fallback.
SOURCE_THEME_DIR="$REPO_ROOT/themes/$THEME_NAME"
if [ ! -d "$SOURCE_THEME_DIR" ]; then
  SOURCE_THEME_DIR="$REPO_ROOT/themes/saga-$THEME_NAME"
fi

if [ ! -d "$SOURCE_THEME_DIR" ]; then
  echo "[ERROR] Theme not found: $THEME_NAME"
  exit 1
fi

TARGET_THEME_DIR="$THEMES_DIR/$THEME_NAME"
RESOLVED_THEME_NAME="$(basename "$SOURCE_THEME_DIR")"
TARGET_THEME_DIR="$THEMES_DIR/$RESOLVED_THEME_NAME"
THEME_JSON="$TARGET_THEME_DIR/theme.json"
THEME_VARS_CSS="$TARGET_THEME_DIR/variables.css"

echo "Applying theme: $RESOLVED_THEME_NAME"
mkdir -p "$THEMES_DIR" "$WIDGETS_DIR" "$FUTURE_RENDERER_DIR" "$SAGA_CONFIG_DIR" "$HYPR_CONFIG_DIR" "$WOFI_CONFIG_DIR" "$SWAYNC_CONFIG_DIR"

rm -rf "$TARGET_THEME_DIR"
cp -a "$SOURCE_THEME_DIR" "$TARGET_THEME_DIR"

# Central theme contract:
# theme.json is the single source of truth for branding values.
if ! command -v jq >/dev/null 2>&1; then
  echo "[ERROR] jq is required to apply themes from theme.json" >&2
  exit 1
fi
if [ ! -f "$THEME_JSON" ]; then
  echo "[ERROR] Missing theme.json in theme: $THEME_JSON" >&2
  exit 1
fi

primary="$(jq -r '.colors.primary' "$THEME_JSON")"
secondary="$(jq -r '.colors.secondary' "$THEME_JSON")"
accent="$(jq -r '.colors.accent' "$THEME_JSON")"
background="$(jq -r '.colors.background' "$THEME_JSON")"
glass="$(jq -r '.colors.glass' "$THEME_JSON")"
text="$(jq -r '.colors.text' "$THEME_JSON")"
text_muted="$(jq -r '.colors["text-muted"]' "$THEME_JSON")"
font_ui="$(jq -r '.fonts.ui' "$THEME_JSON")"
font_size="$(jq -r '.fonts.size' "$THEME_JSON")"
radius="$(jq -r '.ui.radius' "$THEME_JSON")"
border_size="$(jq -r '.ui.border_size' "$THEME_JSON")"
blur="$(jq -r '.ui.blur' "$THEME_JSON")"
anim_windows="$(jq -r '.animations.windows' "$THEME_JSON")"
anim_workspace="$(jq -r '.animations.workspace' "$THEME_JSON")"

# Theme-specific behavior flags.
# Cyberpunk gets glass/translucent windows; default stays opaque.
is_cyberpunk=0
if [[ "$RESOLVED_THEME_NAME" == "saga-cyberpunk" || "$RESOLVED_THEME_NAME" == "cyberpunk" ]]; then
  is_cyberpunk=1
fi

active_opacity="1.0"
inactive_opacity="1.0"
fullscreen_opacity="1.0"
if [[ "$is_cyberpunk" -eq 1 ]]; then
  active_opacity="0.94"
  inactive_opacity="0.88"
  fullscreen_opacity="1.0"
fi

cat > "$THEME_VARS_CSS" <<CSS
:root {
  --saga-primary: $primary;
  --saga-secondary: $secondary;
  --saga-accent: $accent;
  --saga-bg: $background;
  --saga-glass: $glass;
  --saga-text: $text;
  --saga-text-muted: $text_muted;
  --saga-font-ui: "$font_ui";
  --saga-font-size: ${font_size}px;
  --saga-radius: ${radius}px;
  --saga-border-size: ${border_size}px;
  --saga-blur: ${blur}px;
}
CSS

# Hyprland theme rendering from theme.json values.
cat > "$HYPR_THEME_FILE" <<HYPR
# Generated by saga theme apply ($RESOLVED_THEME_NAME)

general {
  border_size = $border_size
  col.active_border = rgb(${primary#\#}) rgb(${secondary#\#}) 45deg
  col.inactive_border = rgb(${accent#\#})
}

decoration {
  rounding = $radius
  active_opacity = $active_opacity
  inactive_opacity = $inactive_opacity
  fullscreen_opacity = $fullscreen_opacity

  blur {
    enabled = $( [ "$blur" -gt 0 ] && echo "true" || echo "false" )
    size = $blur
    passes = 2
    ignore_opacity = true
  }

  shadow {
    enabled = $( [ "$blur" -gt 0 ] && echo "true" || echo "false" )
    render_power = 3
    color = rgba(157,78,221,0.35)
  }
}

animations {
  enabled = true
  animation = windows,1,$anim_windows,default
  animation = fade,1,$anim_windows,default
  animation = workspaces,1,$anim_workspace,default
}
HYPR

# Launcher styling is also rendered from the same theme variable source.
if [ -f "$TARGET_THEME_DIR/launcher.css" ]; then
  cat "$THEME_VARS_CSS" "$TARGET_THEME_DIR/launcher.css" > "$WOFI_STYLE_FILE"
fi

# Notifications styling from the same theme contract.
cat > "$SWAYNC_STYLE_FILE" <<CSS
* {
  font-family: "$font_ui";
  font-size: ${font_size}px;
}

.notification,
.control-center {
  background: $glass;
  color: $text;
  border: ${border_size}px solid $primary;
  border-radius: ${radius}px;
}

.notification .summary {
  color: $text;
  font-weight: 700;
}

.notification .body {
  color: $text_muted;
}

.notification.critical {
  border-color: $accent;
}

.control-center .notification-row:focus,
.control-center .notification-row:hover {
  background: rgba(255, 255, 255, 0.06);
}

.widget-title,
.widget-label {
  color: $secondary;
}
CSS

echo "Installed theme: $TARGET_THEME_DIR"
echo "Applied Hyprland theme: $HYPR_THEME_FILE"
echo "Applied SwayNC theme: $SWAYNC_STYLE_FILE"
echo "Renderer widgets are currently disabled"
echo "$RESOLVED_THEME_NAME" > "$SAGA_CONFIG_DIR/active-theme"

if command -v hyprctl >/dev/null 2>&1; then
  hyprctl reload >/dev/null 2>&1 || true
fi
if command -v swaync-client >/dev/null 2>&1; then
  swaync-client -rs >/dev/null 2>&1 || true
fi

# Best-effort SDDM theme hook:
# - Theme assets are stored under themes/<theme>/sddm in the repo.
# - System install is attempted only when non-interactive sudo (or root) is available.
SOURCE_SDDM_THEME_DIR="$SOURCE_THEME_DIR/sddm"
if [ -d "$SOURCE_SDDM_THEME_DIR" ]; then
  echo "Found SDDM theme assets for: $RESOLVED_THEME_NAME"
  if [ "$(id -u)" -eq 0 ]; then
    mkdir -p "$SDDM_THEME_ROOT" "$SDDM_THEME_CONF_DIR"
    rm -rf "$SDDM_THEME_ROOT/$RESOLVED_THEME_NAME"
    cp -a "$SOURCE_SDDM_THEME_DIR" "$SDDM_THEME_ROOT/$RESOLVED_THEME_NAME"
    cat > "$SDDM_THEME_CONF_FILE" <<EOF
[Theme]
Current=$RESOLVED_THEME_NAME
EOF
    echo "Applied SDDM theme: $RESOLVED_THEME_NAME"
  elif command -v sudo >/dev/null 2>&1 && sudo -n true >/dev/null 2>&1; then
    sudo mkdir -p "$SDDM_THEME_ROOT" "$SDDM_THEME_CONF_DIR"
    sudo rm -rf "$SDDM_THEME_ROOT/$RESOLVED_THEME_NAME"
    sudo cp -a "$SOURCE_SDDM_THEME_DIR" "$SDDM_THEME_ROOT/$RESOLVED_THEME_NAME"
    sudo tee "$SDDM_THEME_CONF_FILE" >/dev/null <<EOF
[Theme]
Current=$RESOLVED_THEME_NAME
EOF
    echo "Applied SDDM theme: $RESOLVED_THEME_NAME"
  else
    echo "[WARN] Skipping system SDDM theme apply (requires sudo)."
    echo "[INFO] Run 'sudo -v && ./cli/saga theme $THEME_NAME' to apply login theme now."
  fi
fi
